### ISSUE TITLE
Meteor Crashes After Trying to Add OrionJS Relationship

### ISSUE THREAD

**Issue by jeremyhodges** [orionjs/orion#113]
```
W20150420-18:00:35.083(-4)? (STDERR) 
W20150420-18:00:35.083(-4)? (STDERR) /Users/jeremyhodges/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150420-18:00:35.083(-4)? (STDERR) 						throw(ex);
W20150420-18:00:35.083(-4)? (STDERR) 						      ^
W20150420-18:00:35.103(-4)? (STDERR) TypeError: Cannot read property 'collection' of undefined
W20150420-18:00:35.104(-4)? (STDERR)     at Object.orion.attributes.registerAttribute.getSchema (packages/orionjs:relationships/hasOne/main.js:24:1)
W20150420-18:00:35.104(-4)? (STDERR)     at Object.orion.attribute (packages/orionjs:core/attributes/common.js:33:1)
W20150420-18:00:35.104(-4)? (STDERR)     at app/orion/entities/donations.js:6:18
W20150420-18:00:35.104(-4)? (STDERR)     at app/orion/entities/donations.js:29:3
W20150420-18:00:35.104(-4)? (STDERR)     at /Users/jeremyhodges/Dropbox/Websites/Love Africa/donate/.meteor/local/build/programs/server/boot.js:222:10
W20150420-18:00:35.104(-4)? (STDERR)     at Array.forEach (native)
W20150420-18:00:35.104(-4)? (STDERR)     at Function._.each._.forEach (/Users/jeremyhodges/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150420-18:00:35.104(-4)? (STDERR)     at /Users/jeremyhodges/Dropbox/Websites/Love Africa/donate/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

```javascript

orion.addEntity('donations', {
    name: {
        type: String
    },
    group: orion.attribute('hasOne', {
        label: 'Student'
    }, {
        entity: 'students',
        titleField: 'name',
        publicationName: 'youCanPutAnyStringYouWantHere',
        /**
         * To return only the group the the current user has created
         */
        filter: function(userId) {
            return { createdBy: userId };
        }
    })
},  {
    icon: 'money',
    sidebarName: 'Donations',
    pluralName: 'Donations',
    singularName: 'Donation',
    tableColumns: [
        { data:'name', title: 'Donor' }
    ]
});
```

**Comment by nicolaslopezj** [comment]
The child collection must be defined after the parent

**Comment by jeremyhodges** [comment]
@nicolaslopezj I am super new to Meteor. How is this usually handled? Just in the file naming convention of the JavaScript files my entities are created in?

**Comment by rwatts3** [comment]
@jeremyhodges 
change `entity` to `collection` and pass the collection as an object without the `strings`

```js

orion.addEntity('donations', {
    name: {
        type: String
    },
    group: orion.attribute('hasOne', {
        label: 'Student'
    }, {
        collection: students
        titleField: 'name',
        publicationName: 'youCanPutAnyStringYouWantHere',
        /**
         * To return only the group the the current user has created
         */
        filter: function(userId) {
            return { createdBy: userId };
        }
    })
},  {
    icon: 'money',
    sidebarName: 'Donations',
    pluralName: 'Donations',
    singularName: 'Donation',
    tableColumns: [
        { data:'name', title: 'Donor' }
    ]
});

```

**Comment by jeremyhodges** [comment]
@rwatts3 That that gives me an error about 'students' being undefined. If I rename my donations.js file to z_donations.js so it comes after students.js it seems to work. Issue now is my "name" in students is an object consisting of name.first and name.last so the dropdown in the admin is blank.

**Comment by rwatts3** [comment]
Try using numbers. 
1donations
2students

**Comment by rwatts3** [comment]
do you have a repo I can clone to further assist ?

**Comment by jeremyhodges** [comment]
@rwatts3 Sure thing! https://github.com/jeremyhodges/flaming-ninja

I'm also having another strange issue with my entities randomly disappearing from the admin.

**Comment by rwatts3** [comment]
Ok give me a few hours I'll be back online shortly.  Also join the chat here 

https://github.com/orionjs/orion

And I'll help you work through the issues.
