### ISSUE TITLE
Recursive schemas?

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#123]
Congrats on v1 it's really looking good, now I can get back to my ideas :) One of which is to add "Organization" entity/schema so that every Organization can have:

- owner
- admins
- members 
- sub organizations -> This is where I was trying to do a recursive schema but getting some errors.

Below is the code, and here is the fork (v1.0 branch). https://github.com/mraak/example-blog-orgs

I'm getting an error so I wonder if this is possible in the first place. 

Organizations.attachSchema(new SimpleSchema({
  name: {
    type: String
  },

  owner: orion.attribute('user', {
    label: 'Owner'
  },{
    publicationName: 'owner',
  }),

  admins: orion.attribute('users', {
    label: 'Admins'
  },{
    publicationName: 'admins',
  }),

  members: orion.attribute('users', {
    label: 'Members'
  },{
    publicationName: 'members',
  }),

  suborgs: orion.attribute('hasMany', {
    label: 'Sub Organizations'
  },{
    collection: Organizations,
    publicationName: 'suborgs'
  }),

  /**
   * The file attribute is a custom orion attribute
   * This is where orion do the magic. Just set
   * the attribute type and it will automatically
   * create the form for the file.
   * WARNING: the url of the image will not be saved in
   * .image, it will be saved in .image.url.
   */
  logo: orion.attribute('file', {
      label: 'Logo',
      optional: true
  }),
  /**
   * Here its the same with image attribute.
   * summernote is a html editor.
   */
  description: orion.attribute('summernote', {
      label: 'Description'
  }),
  /**
   * This attribute sets the user id of the user that created
   * this post automatically.
   */
  createdBy: orion.attribute('createdBy'),
  createdAt: orion.attribute('createdAt')
}));

**Comment by nicolaslopezj** [comment]
I don't know if this is possible, haven't tested, but it could be possible. 
Can you share the error?

**Comment by mraak** [comment]
W20150504-16:49:29.408(2)? (STDERR)           
W20150504-16:49:29.410(2)? (STDERR) /Users/alenbalja/.meteor/packages/meteor-tool/.1.1.3.1570xzu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150504-16:49:29.410(2)? (STDERR) 						throw(ex);
W20150504-16:49:29.411(2)? (STDERR) 						      ^
W20150504-16:49:29.411(2)? (STDERR) Error: Match error: Missing key 'titleField'
W20150504-16:49:29.411(2)? (STDERR)     at packages/check/match.js:312:1
W20150504-16:49:29.411(2)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150504-16:49:29.411(2)? (STDERR)     at checkSubtree (packages/check/match.js:311:1)
W20150504-16:49:29.412(2)? (STDERR)     at check (packages/check/match.js:32:1)
W20150504-16:49:29.412(2)? (STDERR)     at getSchema (packages/orionjs:relationships/attribute.js:2:1)
W20150504-16:49:29.412(2)? (STDERR)     at Object.orion.attributes.registerAttribute.getSchema (packages/orionjs:relationships/attribute.js:100:1)
W20150504-16:49:29.412(2)? (STDERR)     at Object.orion.attribute (packages/orionjs:attributes/attributes.js:20:1)
W20150504-16:49:29.412(2)? (STDERR)     at app/orion/collections/organizations.js:65:18
W20150504-16:49:29.413(2)? (STDERR)     at app/orion/collections/organizations.js:112:3
W20150504-16:49:29.413(2)? (STDERR)     at /Users/alenbalja/Projects/Code/orionjs/example-blog-orgs/.meteor/local/build/programs/server/boot.js:222:10
=> Exited with code: 8
