### ISSUE TITLE
Argument checking fails with orionjs:pages

### ISSUE THREAD

**Issue by PEM--** [orionjs/orion#145]
Just add `meteor add audit-argument-checks` to your project. Now when you hop in a page, the server complains about an issue on arguments not being checked:
```bash
Exception from sub pages id JoDkvB7ER2DhSCNPE Error: Did not check() all arguments during publisher 'pages'
    at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
    at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
    at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
    at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
    at packages/ddp/livedata_server.js:546:1
```

**Comment by nicolaslopezj** [comment]
This is fixed in v1.1, just wait for the release.
