### ISSUE TITLE
Error, can't save simple dictionary field

### ISSUE THREAD

**Issue by ffxsam** [orionjs/orion#220]
This is my code:

Template:
```
<template name="homePage">
  <div class="container">
    {{ dict 'site.desc' 'No description' }}
  </div>
</template>
```

JS:
```
Meteor.startup(function () {
  orion.dictionary.addDefinition('desc', 'site', {
    type: String,
    label: 'Description'
  });
});
```

Error:

```
I20150703-09:31:19.137(-7)? Exception while invoking method '/dictionary/update' TypeError: Cannot read property '_firstLevelSchemaKeys' of null
I20150703-09:31:19.137(-7)?     at Object.orion.dictionary.deny.insert (packages/orionjs:dictionary/dictionary.js:21:1)
I20150703-09:31:19.137(-7)?     at packages/nicolaslopezj:roles/roles.js:146:1
I20150703-09:31:19.137(-7)?     at Array.forEach (native)
I20150703-09:31:19.137(-7)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150703-09:31:19.137(-7)?     at Object.Roles.helper (packages/nicolaslopezj:roles/roles.js:144:1)
I20150703-09:31:19.137(-7)?     at orion.dictionary.deny.update (packages/orionjs:dictionary/dictionary.js:63:1)
I20150703-09:31:19.138(-7)?     at packages/mongo/collection.js:1045:1
I20150703-09:31:19.138(-7)?     at Array.some (native)
I20150703-09:31:19.138(-7)?     at Function._.some._.any (packages/underscore/underscore.js:233:1)
I20150703-09:31:19.138(-7)?     at [object Object].Mongo.Collection._validatedUpdate (packages/mongo/collection.js:1043:1)
```

**Comment by ffxsam** [comment]
Got it, JS belongs in lib/ folder.
