### ISSUE TITLE
Orion 1.4.0 doesn't work in IE10 at all

### ISSUE THREAD

**Issue by ffxsam** [orionjs/orion#260]
http://forums.orionjs.org/t/orion-100-broken-in-ie10/104

`orionjs:accounts@1.4.1` fixes many of the issues. The page displays once again, but there's one last console error:

```
SCRIPT5022: Tabular.Table options must specify collection 
aldeed_tabular.js, line 65 character 5
```

**Comment by nicolaslopezj** [comment]
Is anyone else having this issue?

@ffxsam Please give more details, I don't have IE so I very difficult for me to debug this.

**Comment by ffxsam** [comment]
I'd strongly urge you to download the free virtual machines Microsoft offers for developers:

http://dev.modern.ie/tools/vms/mac/

That's how I tested it, using the Win7 + IE10 virtual machine (runs on VirtualBox, VMware, and Parallels).

**Comment by nicolaslopezj** [comment]
I will test.

Are you sure is not a problem with any collection you made?

**Comment by ffxsam** [comment]
Positive, this is from a fresh meteor project (`meteor create test`) with just the bare minimum packages added (orion and its requirements).

**Comment by ffxsam** [comment]
Still getting just one more error in IE10:

```
SCRIPT5022: Tabular.Table options must specify collection 
aldeed_tabular.js, line 65 character 5
```

Steps taken to get here:

1. `meteor create tmp`
2. `cd tmp`
3. `meteor add iron:router orionjs:core aldeed:tabular`
4. `meteor`
5. Surf to page using IE10, look at the console

**Comment by nicolaslopezj** [comment]
Is this fixed with bootstrap@1.4.2 or materialize@1.4.2?

**Comment by ffxsam** [comment]
I'm using bootstrap. IE10 still fails. Console output:

```
SCRIPT5022: Tabular.Table options must specify collection 
7731d77e9d5a62acfc30a64dc0da341113635704.js, line 217 character 595
SCRIPT5009: 'Spacebars' is undefined 
7731d77e9d5a62acfc30a64dc0da341113635704.js, line 107 character 17375
SCRIPT5009: 'Tracker' is undefined 
7731d77e9d5a62acfc30a64dc0da341113635704.js, line 146 character 17394
SCRIPT5009: 'Spacebars' is undefined 
7731d77e9d5a62acfc30a64dc0da341113635704.js, line 68 character 1371
 Exception in defer callback: Error: no domrange
   at _attachEvents (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:66:5102)
   at events (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:66:4943)
   at d (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:78:2019)
   at constructor (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:80:522)
   at o (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:64:1574)
   at createController (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:80:10791)
   at dispatch (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:80:15970)
   at r (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:80:16993)
   at _compute (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:15:2045)
   at Computation (http://staging.buildsavings.com/7731d77e9d5a62acfc30a64dc0da341113635704.js:15:1275) 
```

**Comment by nicolaslopezj** [comment]
Try this
https://github.com/aldeed/meteor-tabular/issues/170

**Comment by ffxsam** [comment]
I don't know what the "comments" package is, as I don't have that installed. I'm in a serious bind here. :( Under pressure from a client to get this site up, but it completely bombs out in IE10.

I don't have `matb33:collection-hooks` installed (it's probably referenced by a package), but if I do install it manually and move it way up in the list of packages in `.meteor/packages`, I get even more errors.

```
SCRIPT438: Object doesn't support property or method 'helpers' 
nicolaslopezj_roles.js, line 290 character 1
SCRIPT5007: Unable to get property 'Roles' of undefined or null reference 
orionjs_base.js, line 25 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_attributes.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_accounts.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_config.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_collections.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_dictionary.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_core.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_bootstrap.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_filesystem.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_file-attribute.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_image-attribute.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
orionjs_s3.js, line 22 character 1
SCRIPT5007: Unable to get property 'orion' of undefined or null reference 
global-imports.js, line 19 character 1
SCRIPT5009: 'Template' is undefined 
template.gallery-arrows.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.layout.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.not-found.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.featured-prods.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.get-started.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.landing-page.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.loading-spinner.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.product-detail.js, line 2 character 1
SCRIPT5009: 'Template' is undefined 
template.product.js, line 2 character 1
SCRIPT5009: 'Tracker' is undefined 
helpers.es6.js.js, line 2 character 1
SCRIPT5009: 'Mongo' is undefined 
leads.js, line 1 character 13
SCRIPT5009: 'Template' is undefined 
layout.es6.js.js, line 3 character 1
SCRIPT5009: 'Template' is undefined 
featured-prods.es6.js.js, line 1 character 13
SCRIPT5009: 'Template' is undefined 
get-started.es6.js.js, line 1 character 13
SCRIPT5009: 'Template' is undefined 
landing-page.es6.js.js, line 1 character 13
SCRIPT5009: 'Template' is undefined 
product-detail.es6.js.js, line 8 character 1
SCRIPT5009: 'Template' is undefined 
product.es6.js.js, line 1 character 13
SCRIPT5009: 'orion' is undefined 
contact.js, line 1 character 13
SCRIPT5009: 'orion' is undefined 
get-started.js, line 1 character 13
SCRIPT5009: 'orion' is undefined 
header-footer.js, line 6 character 1
SCRIPT5009: 'orion' is undefined 
how-it-works.js, line 1 character 13
SCRIPT5009: 'orion' is undefined 
intro.js, line 1 character 13
SCRIPT5009: 'orion' is undefined 
products.es6.js.js, line 1 character 13
SCRIPT5009: 'Spacebars' is undefined 
accounts-ui-unstyled.js, line 634 character 3
SCRIPT5009: 'Spacebars' is undefined 
iron_layout.js, line 95 character 3
 Exception in defer callback: Error: no domrange
   at _attachEvents (http://192.168.11.11:3000/packages/iron_dynamic-template.js?ccf1d8e4c1e95e99af04ba0ac922dbd8099fb0bd:430:5)
   at events (http://192.168.11.11:3000/packages/iron_dynamic-template.js?ccf1d8e4c1e95e99af04ba0ac922dbd8099fb0bd:414:3)
   at Controller (http://192.168.11.11:3000/packages/iron_controller.js?5a7eedaafda7001b9d5cb52322a419bbb758968c:243:3)
   at constructor (http://192.168.11.11:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:105:5)
   at ctor (http://192.168.11.11:3000/packages/iron_core.js?d966a1f70c94792fd94c8a155bdbef9bec5e0047:159:5)
   at createController (http://192.168.11.11:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:840:3)
   at createController (http://192.168.11.11:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:1130:5)
   at dispatch (http://192.168.11.11:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:1693:5)
   at onLocationChange (http://192.168.11.11:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:1782:7)
   at _compute (http://192.168.11.11:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:5) 
SCRIPT5009: 'Tracker' is undefined 
okgrow_analytics.js, line 168 character 5
```

**Comment by ffxsam** [comment]
Ok, now I removed `matb33:collection-hooks` from `.meteor/packages`. Magically, the page loads fine.. makes no sense!

The only error I get (which doesn't cause any major issues):

> SCRIPT5022: Tabular.Table options must specify collection 
aldeed_tabular.js, line 65 character 5
