### ISSUE TITLE
Problems with server side routes & Orion (v1.4.0)

### ISSUE THREAD

**Issue by jorisroling** [orionjs/orion#294]
Hi All,

I've got a problem with Orion (v1.4.0) and server side routes (Iron Router). The error I (whenever I try the GET route in a browser) get is this: **TypeError: Object function router(req, res, next) ... has no method 'current'** (full error below).

To recreate the setup:
* Create a project with: **meteor create tst**
* cd into tsts with: **cd tst**
* remove the standard files with: **rm tst.css tst.html tst.js**
* create server folder with: **mkdir server**
* create **router.js** file with the following contents:
```js
Router.route('/hello', function () {
  var req = this.request;
  var res = this.response;
  res.end('OK');
}, {where: 'server'});
```

Now add Orion Packages as [follows](http://orionjs.org/docs/introduction) (as the official site explains)

* meteor add orionjs:core
* meteor add twbs:bootstrap fortawesome:fontawesome orionjs:bootstrap
* meteor add iron:router

Now run **meteor**

Now this should result on a (very) simple project, that would respond to the URL **http://localhost:3000/hello** with the text *OK*. Instead it breaks with the server error below.

If I would do this without the Orion packages (just Iron Router), everything works as expected.

Anyone any idea how to get arround this?

Regards,
Joris

###Full error
```
W20150907-11:32:15.185(2)? (STDERR) TypeError: Object function router(req, res, next) {                                                          // 13
W20150907-11:32:15.185(2)? (STDERR)     //XXX this assumes no other routers on the parent stack which we should probably fix      // 14
W20150907-11:32:15.186(2)? (STDERR)     router.dispatch(req.url, {                                                                // 15
W20150907-11:32:15.186(2)? (STDERR)       request: req,                                                                           // 16
W20150907-11:32:15.186(2)? (STDERR)       response: res                                                                           // 17
W20150907-11:32:15.186(2)? (STDERR)     }, next);                                                                                 // 18
W20150907-11:32:15.186(2)? (STDERR)   } has no method 'current'
W20150907-11:32:15.186(2)? (STDERR)     at [object Object].<anonymous> (packages/orionjs:accounts/authentication/secure-routes.js:10:1)
W20150907-11:32:15.186(2)? (STDERR)     at packages/iron:router/lib/router.js:277:1
W20150907-11:32:15.186(2)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150907-11:32:15.186(2)? (STDERR)     at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
W20150907-11:32:15.186(2)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150907-11:32:15.186(2)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150907-11:32:15.186(2)? (STDERR)     at packages/meteor/dynamics_nodejs.js:121:1
W20150907-11:32:15.186(2)? (STDERR)     at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
W20150907-11:32:15.186(2)? (STDERR)     at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
W20150907-11:32:15.187(2)? (STDERR)     at Function.Route.dispatch (packages/iron:router/lib/route.js:156:1)
W20150907-11:32:15.187(2)? (STDERR)     at [object Object].route (packages/iron:router/lib/route.js:13:1)
W20150907-11:32:15.187(2)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150907-11:32:15.187(2)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150907-11:32:15.187(2)? (STDERR)     at packages/meteor/dynamics_nodejs.js:121:1
W20150907-11:32:15.187(2)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:198:1)
W20150907-11:32:15.187(2)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by jorisroling** [comment]
I've proposed a fix for this (pull reguest [#296](https://github.com/orionjs/orion/pull/296)).

**Comment by frabrunelle** [comment]
@nicolaslopezj: Can you please fix this? I also get the same error. I want to use your `excel-export` package, but I get the following error: 

```
W20150914-16:45:34.114(-4)? (STDERR) TypeError: Object function router(req, res, next) {                                                          // 13
W20150914-16:45:34.115(-4)? (STDERR)     //XXX this assumes no other routers on the parent stack which we should probably fix      // 14
W20150914-16:45:34.115(-4)? (STDERR)     router.dispatch(req.url, {                                                                // 15
W20150914-16:45:34.115(-4)? (STDERR)       request: req,                                                                           // 16
W20150914-16:45:34.115(-4)? (STDERR)       response: res                                                                           // 17
W20150914-16:45:34.115(-4)? (STDERR)     }, next);                                                                                 // 18
W20150914-16:45:34.116(-4)? (STDERR)   } has no method 'current'
W20150914-16:45:34.116(-4)? (STDERR)     at [object Object].<anonymous> (packages/orionjs:accounts/authentication/secure-routes.js:10:1)
W20150914-16:45:34.116(-4)? (STDERR)     at packages/iron:router/lib/router.js:277:1
W20150914-16:45:34.116(-4)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150914-16:45:34.116(-4)? (STDERR)     at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
W20150914-16:45:34.116(-4)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150914-16:45:34.116(-4)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150914-16:45:34.116(-4)? (STDERR)     at packages/meteor/dynamics_nodejs.js:121:1
W20150914-16:45:34.116(-4)? (STDERR)     at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
W20150914-16:45:34.116(-4)? (STDERR)     at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
W20150914-16:45:34.116(-4)? (STDERR)     at Function.Route.dispatch (packages/iron:router/lib/route.js:156:1)
```

Thank you very much!

**Comment by frabrunelle** [comment]
For some reason I wasn't at the latest version of `orionjs:accounts` (1.4.2 instead of 1.4.7) and I had to manually update with `meteor update orionjs:accounts`.

Everything works fine now. Cheers!
