### ISSUE TITLE
Tabular publishes to non-admins but does not display data

### ISSUE THREAD

**Issue by pcuci** [orionjs/orion#321]
I'm logged in with an admin account, seems to work as intended :+1: 
![image](https://cloud.githubusercontent.com/assets/2169849/10350792/0afebf38-6d14-11e5-8ecf-bb3899ca3c25.png)

Changing to non-admin user, data is still published to the client, but not displayed by tabular
![image](https://cloud.githubusercontent.com/assets/2169849/10350816/2f839efa-6d14-11e5-9a6c-344a25f02448.png)

Reproduction repo here (specific commit): https://github.com/pcuci/orionjs-practice/commit/ffe643da2b113c0603b1f7e7ca9fcfe5d65fb49d

Getting this error also:

```
I20151007-17:03:37.272(-4)? Exception from sub tabular_getInfo id bRSs32gSJuFbR2icF MongoError: Can't canonicalize query: BadValue $and/$or/$nor must be a nonempty array
I20151007-17:03:37.273(-4)?     at Object.Future.wait (/home/paul/.meteor/packages/meteor-tool/.1.1.9.11la5t4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151007-17:03:37.273(-4)?     at [object Object]._.extend._nextObject (packages/mongo/packages/mongo.js:994:1)
I20151007-17:03:37.273(-4)?     at [object Object]._.extend.forEach (packages/mongo/packages/mongo.js:1028:1)
I20151007-17:03:37.274(-4)?     at [object Object]._.extend.map (packages/mongo/packages/mongo.js:1038:1)
I20151007-17:03:37.274(-4)?     at [object Object].Cursor.(anonymous function) [as map] (packages/mongo/packages/mongo.js:877:1)
I20151007-17:03:37.274(-4)?     at [object Object].Package (packages/nicolaslopezj_tabular-materialize/server/tabular.js:115:1)
I20151007-17:03:37.274(-4)?     at packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:227:1
I20151007-17:03:37.274(-4)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151007-17:03:37.274(-4)?     at [object Object]._handler (packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:226:1)
I20151007-17:03:37.274(-4)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151007-17:03:37.274(-4)?     - - - - -
I20151007-17:03:37.275(-4)?     at Object.toError (/home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20151007-17:03:37.275(-4)?     at /home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:714:54
I20151007-17:03:37.275(-4)?     at Cursor.close (/home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
I20151007-17:03:37.275(-4)?     at commandHandler (/home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:714:21)
I20151007-17:03:37.275(-4)?     at /home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
I20151007-17:03:37.275(-4)?     at Server.Base._callHandler (/home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20151007-17:03:37.275(-4)?     at /home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
I20151007-17:03:37.275(-4)?     at [object Object].MongoReply.parseBody (/home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20151007-17:03:37.276(-4)?     at [object Object].<anonymous> (/home/paul/.meteor/packages/npm-mongo/.1.4.39_1.1elkbsp++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
I20151007-17:03:37.276(-4)?     at [object Object].emit (events.js:95:17)

```

**Comment by nicolaslopezj** [comment]
You should set the index filter to the role.

http://docs.orionjs.org/v1.5/roles

```js
/**
 * Set the index filter.
 * This part is very important and sometimes is forgotten.
 * Here you must specify which documents the role will be able to see in the index route
 */
myRole.helper('collections.myCollection.indexFilter', {}); // Allows the role to se all documents
```
