### ISSUE TITLE
issues about orionjs:pages

### ISSUE THREAD

**Issue by XMT611** [orionjs/orion#401]
Hi everyone: 
I was trying to update/delete the pages that i created. However it didn't work.

I have the terminal errors here:

`I20160328-17:58:42.685(8)? Exception from sub page id 42iHhyRLJfHe4sHgF Error: Match error: Expected string, got object
I20160328-17:58:42.686(8)?     at check (packages/check/match.js:33:1)
I20160328-17:58:42.686(8)?     at [object Object].Meteor.publish.orion.pages.collection.find._id (pages_server.js:8:3)
I20160328-17:58:42.686(8)?     at packages/matb33_collection-hooks/collection-hooks.js:275:1
I20160328-17:58:42.686(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160328-17:58:42.686(8)?     at [object Object]._handler (packages/matb33_collection-hooks/collection-hooks.js:274:1)
I20160328-17:58:42.687(8)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160328-17:58:42.687(8)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20160328-17:58:42.687(8)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20160328-17:58:42.687(8)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20160328-17:58:42.687(8)?     at livedata_server.js:548:43
I20160328-17:58:42.687(8)? Sanitized and reported to the client as: Match failed [400]`

I'm currently using kadira:flow-router 2.10.1.
Is there anything i can do to fix this problem, or it's a bug?
Thanks  XD

**Comment by sean-stanley** [comment]
Maybe in the console have a look at orion.pages.collection.find().fetch() and see if the _id's are all strings? Maybe somehow one ended up as an ObjectId(). Delete that page manually from mongodb either from the console or meteor mongo and try recreating the pages again using the CMS.
