### ISSUE TITLE
orion.collection is messing up

### ISSUE THREAD

**Issue by JustinRvt** [orionjs/orion#421]
Hello.

I wanted to add Orionjs to a project and I experienced a few issues.
According to documentation, I'm supposed to change 
`myCollection = new Mongo.Collection(name, options);`
to
`myCollection = new orion.collection(name, options);`

Problem is: 
```
Error: Match error: Expected object, got undefined
    at exports.check (packages/check/match.js:34:1)
    at new orion.collection (packages/orionjs:collections/new.js:8:3)
    at meteorInstall.orion.collections.cursus.js (orion/collections/cursus.js:1:10)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
```

So I tried to install Orionjs from scratch and the problem persists when I'm using `myCollection= new orion.collection()`
With the normal Mongo syntax, my collections do not appear in the back-office **BUT** it manages users correctly. 

Any hint would be appreciated.
Thanks.

**Comment by JulianKingman** [comment]
@JustinRvt did you get this solved?

**Comment by JulianKingman** [comment]
Ah, the options can't be blank.
