### ISSUE TITLE
TypeError: Cannot read property 'orderable' of undefined

### ISSUE THREAD

**Issue by xuxinlai2016** [orionjs/orion#442]

**Comment by xuxinlai2016** [comment]
W20161103-21:36:51.382(8)? (STDERR) /home/xuxinlai/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161103-21:36:51.382(8)? (STDERR) 						throw(ex);
W20161103-21:36:51.383(8)? (STDERR) 						^
W20161103-21:36:51.383(8)? (STDERR) 
W20161103-21:36:51.384(8)? (STDERR) TypeError: Cannot read property 'orderable' of undefined
W20161103-21:36:51.384(8)? (STDERR)     at Object.orion.attributeColumn (packages/orionjs:attributes/attributes.js:43:7)
W20161103-21:36:51.384(8)? (STDERR)     at meteorInstall.lib.collections.posts.js (lib/collections/posts.js:24:13)
W20161103-21:36:51.385(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161103-21:36:51.385(8)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161103-21:36:51.385(8)? (STDERR)     at /home/xuxinlai/myLedgerBg/.meteor/local/build/programs/server/app/app.js:37:1
W20161103-21:36:51.386(8)? (STDERR)     at /home/xuxinlai/myLedgerBg/.meteor/local/build/programs/server/boot.js:295:34
W20161103-21:36:51.386(8)? (STDERR)     at Array.forEach (native)
W20161103-21:36:51.387(8)? (STDERR)     at Function._.each._.forEach (/home/xuxinlai/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20161103-21:36:51.387(8)? (STDERR)     at /home/xuxinlai/myLedgerBg/.meteor/local/build/programs/server/boot.js:128:5
W20161103-21:36:51.388(8)? (STDERR)     at /home/xuxinlai/myLedgerBg/.meteor/local/build/programs/server/boot.js:344:5

**Comment by jannikkeye** [comment]
I had this error before. If I remember correctly you are missing an attribute package (i.e. file-attribute or image-attribute). Check your collection definitions for attribute columns and find the one you are missing.
`meteor add missing:package`

Hope this helps.

**Comment by inspiraluna** [comment]
I had it too! For me it was the orionjs:summernote module!
